# Robert Antoni Buj Gelonch <rbuj@fedoraproject.org>, 2015. #zanata
# Robert Antoni Buj Gelonch <rbuj@fedoraproject.org>, 2018. #zanata
msgid ""
msgstr ""
"Project-Id-Version: Spacewalk\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2018-03-16 14:32+0100\n"
"PO-Revision-Date: 2018-02-24 11:38-0500\n"
"Last-Translator: Robert Antoni Buj Gelonch <rbuj@fedoraproject.org>\n"
"Language-Team: Catalan\n"
"Language: ca\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=(n != 1)\n"
"X-Generator: Zanata 3.9.6\n"

#: ../server/rhnHandler.py:62
msgid "Please run rhn_register as root on this client"
msgstr ""

#: ../server/rhnHandler.py:75
#, python-format
msgid "Service not enabled for system profile: \"%s\""
msgstr ""

#: ../server/rhnPackage.py:46 ../server/rhnPackage.py:81
#: ../server/rhnPackage.py:101 ../server/rhnPackage.py:152
#, python-format
msgid "Invalid RPM package %s requested"
msgstr ""

#: ../server/rhnPackage.py:106
msgid "Package not found"
msgstr "Paquet no trobat"

#: ../server/handlers/applet/applet.py:78
msgid "Your system was not found in the RHN database"
msgstr ""

#: ../server/handlers/xmlrpc/proxy.py:63
#, python-format
msgid "Spacewalk Proxy service not enabled for server profile: \"%s\""
msgstr ""

#: ../server/handlers/xmlrpc/proxy.py:83
msgid "Invalid session key"
msgstr "la clau de sessió no és vàlida"

#: ../server/handlers/xmlrpc/proxy.py:91
msgid "This server ID no longer exists"
msgstr "Aquest id. de servidor ja no existeix"

#: ../server/handlers/xmlrpc/registration.py:202
msgid "Required data missing"
msgstr ""

#: ../server/handlers/xmlrpc/registration.py:206
msgid "Required members missing"
msgstr ""

#: ../server/handlers/xmlrpc/registration.py:215
msgid "Attempt to register a system to an invalid username"
msgstr ""

#: ../server/handlers/xmlrpc/registration.py:223
#, python-format
msgid ""
"\n"
"                   %s Account has been deactivated on this server.\n"
"                   Please contact your Org administrator for more help."
msgstr ""

#: ../server/handlers/xmlrpc/registration.py:827
msgid "Invalid system release version requested"
msgstr ""

#: ../server/handlers/xmlrpc/registration.py:1059
#, fuzzy
msgid "Red Hat Satellite Welcome Message"
msgstr "Missatge de benvinguda a la Red Hat Network"

#: ../server/handlers/xmlrpc/registration.py:1069
#, fuzzy
msgid "Red Hat Satellite Privacy Statement"
msgstr "Declaració de privacitat de la Red Hat Network"

#: ../server/handlers/xmlrpc/registration.py:1090
msgid "Expected a dictionary as a product argument"
msgstr ""

#: ../server/handlers/xmlrpc/registration.py:1300
#, python-format
msgid "Invalid value '%s' for %s (%s)"
msgstr ""

#: ../server/handlers/xmlrpc/errata.py:62
#, python-format
msgid "Expected a package name, not: %s"
msgstr ""

#: ../server/handlers/xmlrpc/errata.py:113
#, python-format
msgid "Expected a package, not: %s"
msgstr "S'esperava un paquet, no: %s"

#: ../server/handlers/xmlrpc/queue.py:434
#, python-format
msgid "Invalid action value type %s (%s)"
msgstr ""

#: ../server/handlers/xmlrpc/queue.py:459
#, python-format
msgid "Action %s does not belong to server %s"
msgstr "L'acció %s no pertany al servidor %s"

#: ../server/handlers/xmlrpc/scap.py:89
msgid "Invalid system_id/action_id pair."
msgstr ""

#: ../server/handlers/xmlrpc/up2date.py:234
#, python-format
msgid "Invalid value %s (%s)"
msgstr "Valor no vàlid %s (%s)"

#: ../server/handlers/sat/auth.py:45
msgid "ISS is disabled on this satellite."
msgstr "ISS està inhabilitat en aquest satellite."

#: ../server/handlers/sat/auth.py:50
#, python-format
msgid "Server \"%s\" is not enabled for ISS."
msgstr "El servidor \"%s\" no està habilitat per a l'ISS."

#: ../server/rhnServer/server_token.py:77
#, python-format
msgid "Token `%s' has more than one base channel assigned"
msgstr "El testimoni `%s' té més d'un canal base assignat"

#: ../server/rhnServer/server_token.py:79
msgid "Conflicting base channels"
msgstr ""

#: ../server/rhnServer/server_token.py:189
#, python-format
msgid "Failed to add server to group %s"
msgstr ""

#: ../server/rhnServer/server_token.py:502
#, python-format
msgid "Maximum usage count of %s reached"
msgstr ""

#: ../server/rhnServer/server_token.py:733
msgid ""
"Stacking of re-registration tokens with different base entitlements is not "
"supported"
msgstr ""

#: ../server/rhnServer/server_token.py:787
#, python-format
msgid "Could not find token '%s'"
msgstr "No es va poder tovar el testimoni '%s'"

#. Cannot use activation keys from different orgs
#: ../server/rhnServer/server_token.py:819
msgid "Tokens from mismatching orgs"
msgstr ""

#. Two tokens with different kickstart sessions
#: ../server/rhnServer/server_token.py:829
msgid "Kickstart session mismatch"
msgstr ""

#: ../server/rhnServer/server_token.py:849
msgid "Stacking of re-registration tokens is not supported"
msgstr ""

#: ../server/rhnServer/server_class.py:97
#, python-format
msgid "Architecture `%s' is not supported"
msgstr ""

#: ../server/rhnChannel.py:1926
#, python-format
msgid ""
"Your account does not have access to any channels matching "
"(release='%(release)s', arch='%(arch)s')%(www_activation)s"
msgstr ""

#: ../server/rhnChannel.py:1936
msgid ""
"\n"
"If you have a registration number, please register with it first at http://"
"www.redhat.com/apps/activate/ and then try again.\n"
"\n"
msgstr ""

#: ../server/rhnChannel.py:1946
#, python-format
msgid "Insufficient subscription permissions for release (%s, %s"
msgstr ""

#. Various messages that can be reused
#.
#. bretm 02/07/2007 -- when we have better old-client documentation, probably
#. will be safe to get rid of all this crap
#: ../server/rhnChannel.py:2210 ../server/rhnChannel.py:2221
#: ../server/rhnChannel.py:2236
msgid "System Registered but Inactive"
msgstr ""

#: ../server/rhnChannel.py:2211
#, python-format
msgid ""
"\n"
"Invalid Architecture and OS release combination (%s, %s).\n"
"Your system has been registered, but will not receive updates\n"
"because it is not subscribed to a channel. If you have not yet\n"
"activated your product for service, please visit our website at:\n"
"\n"
"     http://www.redhat.com/apps/activate/\n"
"\n"
"...to activate your product."
msgstr ""

#: ../server/rhnChannel.py:2222
#, python-format
msgid ""
"\n"
"Invalid Architecture and OS release combination (%s, %s).\n"
"Your system has been registered, but will not receive updates\n"
"because it could not be subscribed to a base channel.\n"
"Please contact your organization administrator for assistance.\n"
msgstr ""

#: ../server/rhnChannel.py:2229
#, python-format
msgid ""
"\n"
"  This system has been successfully registered, but is not yet entitled\n"
"  to service.  To entitle this system to service, login to the web site at:\n"
"\n"
"  %(entitlement_url)s\n"
msgstr ""

#: ../server/rhnChannel.py:2237
#, python-format
msgid ""
"\n"
"  This system has been successfully registered, but no service entitlements\n"
"  were available.  To entitle this system to service, login to the web site "
"at:\n"
"\n"
"  %(entitlement_url)s\n"
msgstr ""

#: ../server/rhnUser.py:289 ../server/rhnUser.py:292
msgid "Invalid username/password combination"
msgstr ""

#. nope, not reserved either
#: ../server/rhnUser.py:468
#, python-format
msgid "Username `%s' has not been reserved"
msgstr ""

#. New accounts have to specify an e-mail address
#: ../server/rhnUser.py:474
msgid "E-mail address not specified"
msgstr ""

#: ../server/rhnUser.py:510
#, python-format
msgid "username should be at least %d characters"
msgstr ""

#: ../server/rhnUser.py:513
#, python-format
msgid "username should be less than %d characters"
msgstr ""

#: ../server/rhnUser.py:524
#, python-format
msgid "username = `%s', invalid character `%s'"
msgstr ""

#: ../server/rhnUser.py:543
#, python-format
msgid "Please limit your e-mail address to %s chars"
msgstr ""

#: ../server/rhnUser.py:624
#, python-format
msgid "password must be at least %d characters"
msgstr ""

#: ../server/rhnUser.py:627
#, python-format
msgid "Password must be shorter than %d characters"
msgstr ""

#: ../server/rhnUser.py:645
#, python-format
msgid "password contains character `%s'"
msgstr ""

#: ../server/rhnUser.py:652
#, python-format
msgid "username should be at least %d characters long"
msgstr ""

#: ../server/rhnUser.py:663
#, python-format
msgid "Cannot register usernames ending with %s"
msgstr ""

#: ../server/apacheAuth.py:67
#, python-format
msgid "incomplete proxy authentication token: %s"
msgstr "testimoni incomplet del servidor intermediari: %s"

#: ../server/apacheAuth.py:85
#, python-format
msgid "Sent proxy signature %s does not match ours %s."
msgstr ""

#: ../server/apacheAuth.py:120
msgid "declined proxy authentication"
msgstr ""

#: ../server/importlib/userAuth.py:98
msgid "You are not authorized to manage packages in the null org"
msgstr "No esteu autoritzat per gestionar els paquets de l'organització nul·la"

#: ../server/importlib/userAuth.py:103
#, python-format
msgid "You are not allowed to manage packages in the %s org"
msgstr "No esteu autoritzat per gestionar els paquets de l'organització %s"

#: ../server/importlib/userAuth.py:121
msgid "You are not allowed to perform administrative tasks"
msgstr "No esteu autoritzat per realitzar les tasques administratives"

#: ../server/importlib/userAuth.py:144
#, python-format
msgid ""
"You are not allowed to manage channel %s, or that channel does not exist"
msgstr ""
"No esteu autoritzat per gestionar el canal %s, o no existeix aquest canal"

#: ../server/apacheRequest.py:59
#, python-format
msgid "Invalid request received (%s)."
msgstr "Es va rebre una petició no vàlida (%s)."

#: ../server/apacheRequest.py:120
#, python-format
msgid ""
"IMPORTANT MESSAGE FOLLOWS:\n"
"%s"
msgstr ""
"MISSATGE IMPORTANT SEGÜENT:\n"
"%s"

#: ../server/apacheRequest.py:149
#, python-format
msgid ""
"While running '%s': caught\n"
"%s : %s\n"
msgstr ""
"Mentre s'executava '%s': es va capturar\n"
"%s : %s\n"

#: ../server/apacheRequest.py:602
#, python-format
msgid "Invalid URI %s"
msgstr "L'URI %s no és vàlid"

#: ../common/rhnTB.py:205
#, python-format
msgid "ERROR: %s %s: %s"
msgstr "ERROR: %s %s: %s"

#: ../common/rhnTB.py:207
#, python-format
msgid "TRACEBACK: %s"
msgstr ""

#. 0-999: Red Hat client/client-like interaction errors:
#: ../common/rhnException.py:53
msgid "This does not appear to be a valid username."
msgstr ""

#: ../common/rhnException.py:54
msgid "Invalid username and password combination."
msgstr ""

#: ../common/rhnException.py:55
msgid "This login is already taken, or the password is incorrect."
msgstr ""

#: ../common/rhnException.py:56
msgid "Permission denied."
msgstr "Permís denegat."

#: ../common/rhnException.py:57
msgid "Object not found."
msgstr "Objecte no trobat."

#: ../common/rhnException.py:58
msgid "Invalid System Digital ID."
msgstr ""

#: ../common/rhnException.py:59
msgid "Invalid System Credentials."
msgstr ""

#: ../common/rhnException.py:60
msgid "Could not retrieve user data from database."
msgstr ""

#: ../common/rhnException.py:61
msgid "Valid username required."
msgstr "Es requereix un nom d'usuari vàlid."

#: ../common/rhnException.py:62
msgid "Valid password required."
msgstr "Es requereix una contrasenya vàlida."

#: ../common/rhnException.py:63
msgid "Minimum username length violation."
msgstr ""

#: ../common/rhnException.py:64
msgid "Minimum password length violation."
msgstr ""

#: ../common/rhnException.py:65
msgid "The username contains invalid characters."
msgstr "El nom d'usuari conté caràcters no vàlids."

#: ../common/rhnException.py:66
msgid "File not found."
msgstr "Fitxer no trobat."

#: ../common/rhnException.py:67
msgid "Architecture and OS version combination is not supported."
msgstr ""

#: ../common/rhnException.py:68
msgid "Could not retrieve system data from database."
msgstr ""

#: ../common/rhnException.py:69
msgid "Invalid arguments passed to function."
msgstr ""

#: ../common/rhnException.py:70
msgid "Unable to retrieve requested entry."
msgstr ""

#: ../common/rhnException.py:71
msgid "Could not update database entry."
msgstr "No s'ha pogut actualitzar l'entrada de la base de dades."

#: ../common/rhnException.py:72
msgid "Unsupported server architecture."
msgstr "L'arquitectura del servidor no està admesa."

#: ../common/rhnException.py:73
#, python-format
msgid ""
"\n"
"     The anonymous server functionality is no longer available.\n"
"\n"
"     Please re-register this system by running rhn_register\n"
"     as root.\n"
"     Please visit https://%(hostname)s/rhn/systems/SystemEntitlements.do\n"
"     or login at https://%(hostname)s, and from the \"Overview\" tab,\n"
"     select \"Subscription Management\" to enable the service for this "
"system.\n"
"     "
msgstr ""

#: ../common/rhnException.py:82
msgid "Record not available in the database."
msgstr ""

#: ../common/rhnException.py:83
msgid "Invalid value for entry."
msgstr "Valor no vàlid per a l'entrada."

#: ../common/rhnException.py:84
#, python-format
msgid ""
"\n"
"     This system does not have a valid entitlement for Red Hat Satellite.\n"
"     Please visit https://%(hostname)s/rhn/systems/SystemEntitlements.do\n"
"     or login at https://%(hostname)s, and from the \"Overview\" tab,\n"
"     select \"Subscription Management\" to enable the service for this "
"system.\n"
"     "
msgstr ""

#: ../common/rhnException.py:90
msgid "Channel error"
msgstr "Error del canal"

#: ../common/rhnException.py:91
msgid "Client session token is invalid."
msgstr "El testimoni de la sessió del client no és vàlid."

#: ../common/rhnException.py:92
msgid "Client session token has expired."
msgstr "El testimoni de la sessió del client ha vençut."

#: ../common/rhnException.py:93
msgid "You are not authorized to retrieve the requested object."
msgstr ""

#: ../common/rhnException.py:94
msgid "Invalid action"
msgstr "Acció no vàlida"

#: ../common/rhnException.py:95
msgid "You are not allowed to perform administrative tasks on this system."
msgstr ""
"No esteu autoritzat per realitzar les tasques administratives en aquest "
"sistema."

#: ../common/rhnException.py:97
msgid "The system is already subscribed to the specified channel."
msgstr "El sistema ja està subscrit al canal especificat."

#: ../common/rhnException.py:98
msgid "The system is not currently subscribed to the specified channel."
msgstr "El sistema actualment no està subscrit al canal especificat."

#: ../common/rhnException.py:99
msgid "The specified channel does not exist."
msgstr "El canal especificat no existeix."

#: ../common/rhnException.py:100
msgid "Invalid channel version."
msgstr "La versió del canal no és vàlida."

#: ../common/rhnException.py:101
msgid ""
"\n"
"     User group membership limits exceeded.\n"
"\n"
"     The current settings for your account do not allow you to add another\n"
"     user account. Please check with the organization administrator for "
"your\n"
"     account if the maximum number of users allowed to subscribe to server "
"needs\n"
"     to be changed.\n"
"     "
msgstr ""

#: ../common/rhnException.py:109
msgid ""
"\n"
"     System group membership limits exceeded.\n"
"\n"
"     The current settings for your account do not allow you to add another\n"
"     system profile. Please check with the organization administrator for "
"your\n"
"     account for modifying the maximum number of system profiles that can "
"be\n"
"     subscribed to your account.\n"
"     "
msgstr ""

#: ../common/rhnException.py:117
#, fuzzy
msgid ""
"\n"
"     Invalid architecture.\n"
"\n"
"     The architecture of the package is not supported by\n"
"     "
msgstr ""
"\n"
"     Arquitectura no vàlida.\n"
"\n"
"     L'arquitectura del paquet no està admesa per la Red Hat Network\n"
"     "

#: ../common/rhnException.py:122
msgid "Invalid RPM header"
msgstr "Capçalera RPM no vàlida"

#. For the uploading tools
#: ../common/rhnException.py:124
msgid "Invalid information uploaded to the server"
msgstr "Informació no vàlida pujada al servidor"

#: ../common/rhnException.py:125
msgid "Error uploading network interfaces configuration."
msgstr ""
"S'ha produït un error en pujar la configuració de les interfícies de xarxa."

#: ../common/rhnException.py:126
msgid ""
"\n"
"     Package Upload Failed due to uniqueness constraint violation.\n"
"     Make sure the package does not have any duplicate dependencies or\n"
"     does not already exists on the server\n"
"     "
msgstr ""

#: ../common/rhnException.py:131
msgid ""
"\n"
"     The --force rhnpush option is disabled on this server.\n"
"     Please contact your Satellite administrator for more help.\n"
"     "
msgstr ""

#. 60-70: token errors
#: ../common/rhnException.py:137
msgid ""
"\n"
"     The activation token specified could not be found on the server.\n"
"     Please retry with a valid key.\n"
"     "
msgstr ""

#: ../common/rhnException.py:141
msgid "Too many systems registered using this registration token"
msgstr ""
"Hi ha massa sistemes registrats que utilitzen aquest testimoni de "
"registrament"

#: ../common/rhnException.py:142
msgid "Token contains invalid, obsoleted or insufficient settings"
msgstr "El testimoni conté ajustos no vàlids, en desús i insuficients"

#: ../common/rhnException.py:143
msgid "Conflicting activation tokens"
msgstr "Conflicte en els testimonis d'activació"

#. 70-80: channel subscription errors
#: ../common/rhnException.py:146
msgid ""
"\n"
"     No matching base channel found for your system.\n"
"     "
msgstr ""

#: ../common/rhnException.py:149
msgid ""
"\n"
"     You do not have subscription permission to the designated channel.\n"
"     Please refer to your organization's channel or organization\n"
"     administrators for further details.\n"
"     "
msgstr ""

#: ../common/rhnException.py:154
msgid "You can not unsubscribe from base channel."
msgstr "No us podeu de-subscriure del canal base."

#: ../common/rhnException.py:155
msgid "Satellite or Proxy channel can not be subscribed."
msgstr ""

#. 80-90: server group errors
#: ../common/rhnException.py:158
msgid "There was an error while trying to join the system to its groups"
msgstr ""

#. 90-100: entitlement errors
#: ../common/rhnException.py:161
msgid "Unable to entitle system"
msgstr "No es pot donar el dret al sistema"

#. 100-109: e-mail and uuid related faults
#: ../common/rhnException.py:164
msgid "Maximum e-mail length violation."
msgstr ""

#: ../common/rhnException.py:165
msgid "This system has been previously registered."
msgstr ""

#: ../common/rhnException.py:166
msgid "Invalid username"
msgstr "El nom d'usuari no és vàlid"

#. 140-159 applet errors
#: ../common/rhnException.py:169
msgid "Unable to look up server"
msgstr ""

#. 160-179: OSAD errors
#: ../common/rhnException.py:172
msgid "Required argument is missing"
msgstr ""

#. 600-699: RHEL5+ EN errors
#: ../common/rhnException.py:175
msgid "No entitlement information tied to hardware"
msgstr ""

#: ../common/rhnException.py:176
msgid "Installation number is not entitling"
msgstr ""

#. 700-799: Additional user input verification errors.
#: ../common/rhnException.py:179
msgid "Maximum username length violation"
msgstr ""

#: ../common/rhnException.py:180
msgid "Maximum password length violation"
msgstr ""

#: ../common/rhnException.py:181
msgid "This user has read only API access. Action denied."
msgstr ""

#: ../common/rhnException.py:183
msgid "System Name cannot be less than 1 character"
msgstr ""

#. 1000-1999: Proxy specific errors:
#. issued by a Proxy to the client
#: ../common/rhnException.py:187
msgid "Spacewalk Proxy error."
msgstr ""

#: ../common/rhnException.py:188
#, fuzzy
msgid "Spacewalk Proxy unable to login."
msgstr "RHN Proxy va ser incapaç d'iniciar la sessió."

#. issued by a Red Hat Server/Satellite to the proxy
#: ../common/rhnException.py:190
msgid ""
"\n"
"     Spacewalk Proxy system ID does not match a Spacewalk Proxy Server\n"
"     in the database.\n"
"     "
msgstr ""

#: ../common/rhnException.py:194
#, fuzzy
msgid "Spacewalk Proxy session token is invalid."
msgstr "El testimoni de la sessió del RHN Proxy no és vàlid."

#: ../common/rhnException.py:195
#, fuzzy
msgid "Spacewalk Proxy session token has expired."
msgstr "El testimoni de la sessió del RHN Proxy ha vençut."

#. 2000-2999: Red Hat Satellite specific errors:
#: ../common/rhnException.py:199
#, fuzzy
msgid ""
"\n"
"      user creation is not allowed via rhn_register;\n"
"     please contact your sysadmin to have your account created.\n"
"     "
msgstr ""
"\n"
"     La creació de l'usuari del RHN Satellite no està permesa a través de "
"rhn_register;\n"
"     poseu-vos en contacte amb l'administrador del sistema perquè creï el "
"vostre compte.\n"
"     "

#: ../common/rhnException.py:203
msgid ""
"\n"
"     This satellite server is not allowed to use Inter Satellite Sync on "
"this satellite\n"
"     "
msgstr ""
"\n"
"     Aquest servidor de satellite no pot utilitzar la sincronització interna "
"entre els satellite en aquest satellite\n"
"     "

#: ../common/rhnException.py:206
msgid ""
"\n"
"     Inter Satellite Sync is disabled on this satellite.\n"
"     "
msgstr ""
"\n"
"     La sincronització interna entre els satellite està inhabilitada en "
"aquest satellite.\n"
"     "

#. 3000-3999: XML dumper errors:
#: ../common/rhnException.py:211
msgid "Invalid datatype passed"
msgstr "Es va passar un tipus de dades no vàlid"

#: ../common/rhnException.py:212
msgid "Unable to retrieve channel"
msgstr "No es pot recuperar el canal"

#: ../common/rhnException.py:213
msgid "Unable to retrieve package"
msgstr "No es pot recuperar el paquet"

#: ../common/rhnException.py:214
msgid "Unable to retrieve erratum"
msgstr "No es pot recuperar l'errata"

#: ../common/rhnException.py:215
msgid "File is missing"
msgstr "Falta el fitxer"

#: ../common/rhnException.py:216
msgid "Function retrieval error"
msgstr "Error en la recuperació de la funció"

#: ../common/rhnException.py:217
msgid "Function execution error"
msgstr "Error en l'execució de la funció"

#: ../common/rhnException.py:218
msgid "Missing version string"
msgstr "Falta la cadena de la versió"

#: ../common/rhnException.py:219
msgid "Invalid version string"
msgstr "La cadena de la versió no és vàlida"

#: ../common/rhnException.py:220
msgid "Mismatching versions"
msgstr "Les versions no coincideixen"

#: ../common/rhnException.py:221
msgid "Invalid channel version"
msgstr "La versió del canal no és vàlida"

#: ../common/rhnException.py:222
msgid "No comps file for channel"
msgstr "No hi ha el fitxer comps per al canal"

#: ../common/rhnException.py:223
msgid "Unable to retrieve comps file"
msgstr "No es pot recuperar el fitxer comps"

#. 4000 - 4999: config management errors
#: ../common/rhnException.py:226
msgid "Configuration action missing"
msgstr "Falta l'acció de configuració"

#: ../common/rhnException.py:227
msgid "File too large"
msgstr "El fitxer és massa gran"

#: ../common/rhnException.py:228
msgid "File contains binary data"
msgstr "El fitxer conté dades binàries"

#: ../common/rhnException.py:229
msgid "Configuration channel is not empty"
msgstr "El canal de configuració no està buit"

#: ../common/rhnException.py:230
msgid "Permission error"
msgstr "Error de permís"

#: ../common/rhnException.py:231
msgid "Content missing for configuration file"
msgstr "Falta contingut per al fitxer de configuració"

#: ../common/rhnException.py:232
msgid "Template delimiters not specified"
msgstr ""

#: ../common/rhnException.py:233
msgid "Configuration channel does not exist"
msgstr "El canal de configuració no existeix"

#: ../common/rhnException.py:234
msgid "Configuration channel already exists"
msgstr "El canal de configuració ja existeix"

#: ../common/rhnException.py:235
msgid "File missing from configuration channel"
msgstr ""

#: ../common/rhnException.py:236
msgid "Different revision of this file is uploaded"
msgstr ""

#: ../common/rhnException.py:237
msgid "File already uploaded to configuration channel"
msgstr ""

#: ../common/rhnException.py:238
msgid "File size exceeds remaining quota space"
msgstr ""

#: ../common/rhnException.py:239
msgid "Full path of file must be specified"
msgstr ""

#: ../common/rhnException.py:240
msgid "Invalid revision number"
msgstr "El número de revisió no és vàlid"

#: ../common/rhnException.py:241
msgid "Cannot compare files of different file type"
msgstr "No es poden comparar els fitxers de diferent tipus de fitxer"

#. 5000 - 5999: client content uploading errors
#. 5000 - 5099: crash reporting errors
#: ../common/rhnException.py:245
msgid "Crash information is invalid or incomplete"
msgstr ""

#: ../common/rhnException.py:246
msgid "Crash file information is invalid or incomplete"
msgstr ""

#: ../common/rhnException.py:247
msgid "Error composing crash directory path"
msgstr ""

#: ../common/rhnException.py:248
msgid "Error composing crash file path"
msgstr ""

#: ../common/rhnException.py:249 ../common/rhnException.py:256
#, fuzzy
msgid "Invalid content encoding"
msgstr "El codi de l'element no és vàlid"

#: ../common/rhnException.py:250
#, fuzzy
msgid "Invalid crash name"
msgstr "El nom del paquet no és vàlid"

#: ../common/rhnException.py:251
msgid "Crash reporting is disabled for this organization"
msgstr ""

#. 5100 - 5199: scap results reporting error
#: ../common/rhnException.py:253
msgid "SCAP results file transfer is invalid or incomplete"
msgstr ""

#: ../common/rhnException.py:254
msgid "Error composing directory path for detailed SCAP results"
msgstr ""

#: ../common/rhnException.py:255
msgid "Error composing file path for detailed SCAP results"
msgstr ""

#: ../common/rhnException.py:303
msgid ""
"\n"
"     An error has occurred while processing your request. If this problem\n"
"     persists please enter a bug report at bugzilla.redhat.com.\n"
"     If you choose to submit the bug report, please be sure to include\n"
"     details of what you were trying to do when this error occurred and\n"
"     details on how to reproduce this problem.\n"
msgstr ""

#: ../common/rhnException.py:355
#, python-format
msgid ""
"Error Message:\n"
"    %s\n"
msgstr ""
"Missatge d'error:\n"
"    %s\n"

#: ../common/rhnException.py:357
#, python-format
msgid "Error Class Code: %s\n"
msgstr "Codi de la classe d'error: %s\n"

#: ../common/rhnException.py:360
#, python-format
msgid "Error Class Info: %s\n"
msgstr "Informació de la classe d'error: %s\n"

#: ../common/rhnException.py:362
#, python-format
msgid "Explanation: %s"
msgstr "Explicació: %s"

#~ msgid "Not a valid Country: %s"
#~ msgstr "No és un país vàlid: %s"

#~ msgid "Invalid value %s (type %s)"
#~ msgstr "Valor no vàlid %s (tipus %s)"

#~ msgid "Invalid value for %s in package tuple: %s (%s)"
#~ msgstr "Valor no vàlid per %s a la tupla del paquet: %s (%s)"

#~ msgid "Invalid package parameter %s (%s)"
#~ msgstr "El paràmetre del paquet no és vàlid %s (%s)"

#~ msgid "Can not create new entry."
#~ msgstr "No es pot crear una nova entrada."

#~ msgid "Invalid product registration code."
#~ msgstr "El codi de registrament del producte no és vàlid."

#~ msgid "LDAP operation failed."
#~ msgstr "L'operació LDAP ha fallat."

#~ msgid ""
#~ "\n"
#~ "     Invalid channel.\n"
#~ "\n"
#~ "     The channel you have specified does not exist.\n"
#~ "     "
#~ msgstr ""
#~ "\n"
#~ "     Canal no vàlid.\n"
#~ "\n"
#~ "     El canal que heu especificat no existeix.\n"
#~ "     "

#~ msgid ""
#~ "Registration token unable to entitle system: maximum membership exceeded"
#~ msgstr ""
#~ "El testimoni de registrament va ser incapaç de donar el dret del sistema: "
#~ "es va superar la màxima afiliació"

#~ msgid "Not an RPM package"
#~ msgstr "No és un paquet RPM"

#~ msgid "Unsigned RPM package"
#~ msgstr "Paquet RPM sense signar"

#~ msgid "Incompatible checksum type"
#~ msgstr "Tipus de checksum incompatible"

#~ msgid ""
#~ "\n"
#~ "     This satellite server is not allowed to access the specified "
#~ "channel\n"
#~ "     "
#~ msgstr ""
#~ "\n"
#~ "     Aquest servidor de satellite no pot accedir al canal especificat\n"
#~ "     "

#~ msgid "Access denied to kickstart tree"
#~ msgstr "Es va denegar l'accés a l'arbre de kickstart"

#~ msgid "Could not find kickstart file"
#~ msgstr "No es va poder trobar el fitxer de kickstart"

#~ msgid "Invalid erratum name"
#~ msgstr "El nom de l'errata no és vàlid"

#~ msgid "Invalid satellite certificate"
#~ msgstr "El certificat del satellite no és vàlid"

#~ msgid "Missing snapshot for channels"
#~ msgstr "Falta la instantània per al canal"

#~ msgid "Invalid user role"
#~ msgstr "El rol de l'usuari no és vàlid"

#~ msgid "Invalid server group"
#~ msgstr "El grup del servidor no és vàlid"

#~ msgid "Invalid channel family"
#~ msgstr "La família del canal no és vàlida"
