# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
#
# Translators:
# Bernd Groh <bgroh@redhat.com>, 2003.
# Gerd Koenig <koenig.ulm@googlemail.com>, 2012.
# Miroslav Suchý <msuchy@redhat.com>, 2011.
# sknirT omiT <moc.tahder@sknirtt>, 2010.
# Timo Trinks <ttrinks@redhat.com>, 2006.
# Verena <vfuehrer@redhat.com>, 2004-2005.
msgid ""
msgstr ""
"Project-Id-Version: Spacewalk\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2016-11-07 18:08+0100\n"
"PO-Revision-Date: 2015-03-17 08:03-0400\n"
"Last-Translator: Copied by Zanata <copied-by-zanata@zanata.org>\n"
"Language-Team: German <trans-de@lists.fedoraproject.org>\n"
"Language: de\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"
"X-Generator: Zanata 3.9.6\n"

#: ../server/rhnHandler.py:62
msgid "Please run rhn_register as root on this client"
msgstr ""

#: ../server/rhnHandler.py:75
#, python-format
msgid "Service not enabled for system profile: \"%s\""
msgstr "Der Dienst ist für das Systemprofil: \"%s\" nicht aktiviert"

#: ../server/rhnPackage.py:46 ../server/rhnPackage.py:81
#: ../server/rhnPackage.py:101 ../server/rhnPackage.py:152
#, python-format
msgid "Invalid RPM package %s requested"
msgstr "ungültiges rpm Paket %s angefordert"

#: ../server/rhnPackage.py:106
msgid "Package not found"
msgstr "Paket nicht gefunden"

#: ../server/rhnChannel.py:1926
#, python-format
msgid ""
"Your account does not have access to any channels matching "
"(release='%(release)s', arch='%(arch)s')%(www_activation)s"
msgstr ""

#: ../server/rhnChannel.py:1936
msgid ""
"\n"
"If you have a registration number, please register with it first at http://"
"www.redhat.com/apps/activate/ and then try again.\n"
"\n"
msgstr ""

#: ../server/rhnChannel.py:1946
#, python-format
msgid "Insufficient subscription permissions for release (%s, %s"
msgstr "Ungenügende Berechtigung für Release (%s, %s"

#. Various messages that can be reused
#.
#. bretm 02/07/2007 -- when we have better old-client documentation, probably
#. will be safe to get rid of all this crap
#: ../server/rhnChannel.py:2210 ../server/rhnChannel.py:2221
#: ../server/rhnChannel.py:2236
msgid "System Registered but Inactive"
msgstr "System registriert, aber inaktiv"

#: ../server/rhnChannel.py:2211
#, fuzzy, python-format
msgid ""
"\n"
"Invalid Architecture and OS release combination (%s, %s).\n"
"Your system has been registered, but will not receive updates\n"
"because it is not subscribed to a channel. If you have not yet\n"
"activated your product for service, please visit our website at:\n"
"\n"
"     http://www.redhat.com/apps/activate/\n"
"\n"
"...to activate your product."
msgstr ""
"\n"
"Ungültige Kombination aus Architektur und Betriebssystemversion (%s, %s).\n"
"Ihr System wurde registriert, wird aber keine Updates erhalten, da es "
"keinen\n"
"Channel abonniert hat. Falls Sie Ihr System bislang nicht aktiviert haben,\n"
"besuchen Sie bitte unsere Webseite unter:\n"
"  \n"
"     http://www.redhat.com/apps/activate/\n"
"\n"
"...um Ihr Produkt zu aktivieren."

#: ../server/rhnChannel.py:2222
#, python-format
msgid ""
"\n"
"Invalid Architecture and OS release combination (%s, %s).\n"
"Your system has been registered, but will not receive updates\n"
"because it could not be subscribed to a base channel.\n"
"Please contact your organization administrator for assistance.\n"
msgstr ""
"\n"
"Ungültige Kombination aus Architektur und Betriebssystemversion (%s, %s).\n"
"Ihr System wurde registriert, wird aber keine Updates erhalten da es keinen\n"
"Basis-Channel abonnieren konnte.\n"
"Bitte kontaktieren Sie zwecks Unterstützung den Org-Administrator.\n"

#: ../server/rhnChannel.py:2229
#, python-format
msgid ""
"\n"
"  This system has been successfully registered, but is not yet entitled\n"
"  to service.  To entitle this system to service, login to the web site at:\n"
"\n"
"  %(entitlement_url)s\n"
msgstr ""

#: ../server/rhnChannel.py:2237
#, python-format
msgid ""
"\n"
"  This system has been successfully registered, but no service entitlements\n"
"  were available.  To entitle this system to service, login to the web site "
"at:\n"
"\n"
"  %(entitlement_url)s\n"
msgstr ""

#: ../server/apacheAuth.py:67
#, python-format
msgid "incomplete proxy authentication token: %s"
msgstr "unvollständige Kennung zur Proxyauthentisierung: %s"

#: ../server/apacheAuth.py:85
#, python-format
msgid "Sent proxy signature %s does not match ours %s."
msgstr "die gesendete Proxysignatur %s stimmt mit unserer (%s) nicht überein"

#: ../server/apacheAuth.py:120
msgid "declined proxy authentication"
msgstr "abgewiesene Proxyauthentisierung"

#: ../server/handlers/sat/auth.py:45
msgid "ISS is disabled on this satellite."
msgstr "ISS ist auf diesem Satellite deaktiviert."

#: ../server/handlers/sat/auth.py:50
#, python-format
msgid "Server \"%s\" is not enabled for ISS."
msgstr "Server \"%s\" nicht für ISS aktiviert."

#: ../server/handlers/xmlrpc/up2date.py:236
#, python-format
msgid "Invalid value %s (%s)"
msgstr "Ungültiger Wert %s (%s)"

#: ../server/handlers/xmlrpc/scap.py:89
#, fuzzy
msgid "Invalid system_id/action_id pair."
msgstr "Ungültige System-Berechtigungsnachweise."

#: ../server/handlers/xmlrpc/proxy.py:64
#, fuzzy, python-format
msgid "Spacewalk Proxy service not enabled for server profile: \"%s\""
msgstr "RHN-Proxy-Dienst nicht für Server-Profil \"%s\" aktiviert"

#: ../server/handlers/xmlrpc/proxy.py:84
msgid "Invalid session key"
msgstr "Ungültiger Sitzungsschlüssel"

#: ../server/handlers/xmlrpc/proxy.py:92
msgid "This server ID no longer exists"
msgstr "Diese Server-ID existiert nicht mehr"

#: ../server/handlers/xmlrpc/registration.py:202
msgid "Required data missing"
msgstr "Erforderliche Daten nicht vorhanden"

#: ../server/handlers/xmlrpc/registration.py:206
msgid "Required members missing"
msgstr "Erforderliche Mitglieder fehlen"

#: ../server/handlers/xmlrpc/registration.py:215
msgid "Attempt to register a system to an invalid username"
msgstr "Versuch, ein System mit einem ungültigen Benutzernamen zu registrieren"

#: ../server/handlers/xmlrpc/registration.py:223
#, python-format
msgid ""
"\n"
"                   %s Account has been deactivated on this server.\n"
"                   Please contact your Org administrator for more help."
msgstr ""
"\n"
"                   %s Benutzer wurde auf diesem Server deaktiviert.\n"
"                   Bitte kontaktieren Sie Ihren Org-Administrator für Hilfe."

#: ../server/handlers/xmlrpc/registration.py:796
msgid "Invalid system release version requested"
msgstr "Ungültige System-Release-Version angefordert"

#: ../server/handlers/xmlrpc/registration.py:1028
#, fuzzy
msgid "Red Hat Satellite Welcome Message"
msgstr "Red Hat Network Willkommensmitteilung"

#: ../server/handlers/xmlrpc/registration.py:1038
#, fuzzy
msgid "Red Hat Satellite Privacy Statement"
msgstr "Red Hat Network Privatsphäre"

#: ../server/handlers/xmlrpc/registration.py:1059
msgid "Expected a dictionary as a product argument"
msgstr "Es wurde ein Wörterbuch als Produktargument erwartet"

#: ../server/handlers/xmlrpc/registration.py:1269
#, python-format
msgid "Invalid value '%s' for %s (%s)"
msgstr "Ungültiger Wert '%s' für %s (%s)"

#: ../server/handlers/xmlrpc/errata.py:62
#, python-format
msgid "Expected a package name, not: %s"
msgstr "Paketname erwartet, nicht: %s"

#: ../server/handlers/xmlrpc/errata.py:113
#, python-format
msgid "Expected a package, not: %s"
msgstr "Paket erwartet, nicht: %s"

#: ../server/handlers/xmlrpc/queue.py:434
#, python-format
msgid "Invalid action value type %s (%s)"
msgstr "Ungültiger Aktionswerttyp %s (%s)"

#: ../server/handlers/xmlrpc/queue.py:459
#, python-format
msgid "Action %s does not belong to server %s"
msgstr "Aktion %s gehört nicht zu Server %s"

#: ../server/handlers/applet/applet.py:78
msgid "Your system was not found in the RHN database"
msgstr "Ihr System wurde in der RHN Datenbank nicht gefunden"

#: ../server/apacheRequest.py:59
#, python-format
msgid "Invalid request received (%s)."
msgstr "Ungültige Anfrage erhalten (%s)."

#: ../server/apacheRequest.py:120
#, python-format
msgid ""
"IMPORTANT MESSAGE FOLLOWS:\n"
"%s"
msgstr ""
"NACHFOLGEND EINE WICHTIGE NACHRICHT:\n"
"%s"

#: ../server/apacheRequest.py:149
#, python-format
msgid ""
"While running '%s': caught\n"
"%s : %s\n"
msgstr ""

#: ../server/apacheRequest.py:602
#, python-format
msgid "Invalid URI %s"
msgstr "Ungültige URI %s"

#: ../server/rhnServer/server_token.py:77
#, python-format
msgid "Token `%s' has more than one base channel assigned"
msgstr "Kennung '%s' hat mehr als einen zugewiesenen Channel"

#: ../server/rhnServer/server_token.py:79
msgid "Conflicting base channels"
msgstr "Konflikt zwischen Basis-Channels"

#: ../server/rhnServer/server_token.py:189
#, python-format
msgid "Failed to add server to group %s"
msgstr "Fehler beim Hinzufügen des Servers zur Gruppe %s"

#: ../server/rhnServer/server_token.py:502
#, python-format
msgid "Maximum usage count of %s reached"
msgstr "Maximale Nutzung von %s erreicht"

#: ../server/rhnServer/server_token.py:733
msgid ""
"Stacking of re-registration tokens with different base entitlements is not "
"supported"
msgstr ""

#: ../server/rhnServer/server_token.py:787
#, python-format
msgid "Could not find token '%s'"
msgstr "Konnte Token '%s' nicht finden"

#. Cannot use activation keys from different orgs
#: ../server/rhnServer/server_token.py:819
msgid "Tokens from mismatching orgs"
msgstr "Tokens von nicht übereinstimmenden Orgs"

#. Two tokens with different kickstart sessions
#: ../server/rhnServer/server_token.py:829
msgid "Kickstart session mismatch"
msgstr "Kickstart-Sitzung stimmt nicht überein"

#: ../server/rhnServer/server_token.py:849
msgid "Stacking of re-registration tokens is not supported"
msgstr ""

#: ../server/rhnServer/server_class.py:97
#, python-format
msgid "Architecture `%s' is not supported"
msgstr "die Architektur '%s' wird nicht unterstützt"

#: ../server/importlib/userAuth.py:98
msgid "You are not authorized to manage packages in the null org"
msgstr "Sie haben keine Berechtigungen, Pakete in der Null-Org zu verwalten"

#: ../server/importlib/userAuth.py:103
#, python-format
msgid "You are not allowed to manage packages in the %s org"
msgstr "Sie dürfen keine Pakete in der %s-Org verwalten"

#: ../server/importlib/userAuth.py:121
msgid "You are not allowed to perform administrative tasks"
msgstr "Sie dürfen keine administrativen Aufgaben durchführen"

#: ../server/importlib/userAuth.py:144
#, python-format
msgid ""
"You are not allowed to manage channel %s, or that channel does not exist"
msgstr ""
"Sie dürfen Channel %s nicht verwalten, oder dieser Channel existiert nicht"

#: ../server/rhnUser.py:289 ../server/rhnUser.py:292
msgid "Invalid username/password combination"
msgstr "Ungültige Kombination von Benutzername und Passwort"

#. nope, not reserved either
#: ../server/rhnUser.py:467
#, python-format
msgid "Username `%s' has not been reserved"
msgstr "der Benutzername '%s' wurde nicht reserviert"

#. New accounts have to specify an e-mail address
#: ../server/rhnUser.py:473
msgid "E-mail address not specified"
msgstr "die Emailadresse wurde nicht angegeben"

#: ../server/rhnUser.py:509
#, python-format
msgid "username should be at least %d characters"
msgstr "der Benutzername muss mindestens %d Zeichen lang sein"

#: ../server/rhnUser.py:512
#, python-format
msgid "username should be less than %d characters"
msgstr "der Benutzername darf höchstens %d Zeichen lang sein"

#: ../server/rhnUser.py:523
#, python-format
msgid "username = `%s', invalid character `%s'"
msgstr "Benutzername = '%s', ungültiges Zeichen '%s'"

#: ../server/rhnUser.py:542
#, python-format
msgid "Please limit your e-mail address to %s chars"
msgstr "Bitte beschränken Sie Ihre Emailadresse auf %s Zeichen"

#: ../server/rhnUser.py:623
#, python-format
msgid "password must be at least %d characters"
msgstr "das Passwort muss mindestens %d Zeichen lang sein"

#: ../server/rhnUser.py:626
#, python-format
msgid "Password must be shorter than %d characters"
msgstr "Das Passwort darf höchstens %d Zeichen lang sein"

#: ../server/rhnUser.py:644
#, python-format
msgid "password contains character `%s'"
msgstr "das Passwort enthält das Zeichen `%s'"

#: ../server/rhnUser.py:651
#, python-format
msgid "username should be at least %d characters long"
msgstr "der Benutzername muss mindestens %d Zeichen lang sein"

#: ../server/rhnUser.py:662
#, python-format
msgid "Cannot register usernames ending with %s"
msgstr "Benutzernamen, die auf %s enden können nicht registriert werden"

#: ../common/rhnTB.py:205
#, python-format
msgid "ERROR: %s %s: %s"
msgstr ""

#: ../common/rhnTB.py:207
#, python-format
msgid "TRACEBACK: %s"
msgstr ""

#. 0-999: Red Hat client/client-like interaction errors:
#: ../common/rhnException.py:53
msgid "This does not appear to be a valid username."
msgstr "Dies scheint kein gültiger Benutzername zu sein."

#: ../common/rhnException.py:54
msgid "Invalid username and password combination."
msgstr "Ungültige Kombination von Benutzername und Passwort"

#: ../common/rhnException.py:55
msgid "This login is already taken, or the password is incorrect."
msgstr "Dieses Login wird bereits verwendet oder das Passwort ist falsch."

#: ../common/rhnException.py:56
msgid "Permission denied."
msgstr "Zugriff verweigert."

#: ../common/rhnException.py:57
msgid "Object not found."
msgstr "Objekt nicht gefunden."

#: ../common/rhnException.py:58
msgid "Invalid System Digital ID."
msgstr "Ungültige System Digital-ID."

#: ../common/rhnException.py:59
msgid "Invalid System Credentials."
msgstr "Ungültige System-Berechtigungsnachweise."

#: ../common/rhnException.py:60
msgid "Could not retrieve user data from database."
msgstr "Benutzerdaten konnten nicht von Datenbank abrufen werden."

#: ../common/rhnException.py:61
msgid "Valid username required."
msgstr "Gültiger Benutzername erforderlich."

#: ../common/rhnException.py:62
msgid "Valid password required."
msgstr "Gültiges Passwort erforderlich."

#: ../common/rhnException.py:63
msgid "Minimum username length violation."
msgstr "Minimallänge des Benutzernamen nicht erfüllt."

#: ../common/rhnException.py:64
msgid "Minimum password length violation."
msgstr "Minimallänge des Passworts nicht erfüllt."

#: ../common/rhnException.py:65
msgid "The username contains invalid characters."
msgstr "Der Benutzername enthält ungültige Zeichen."

#: ../common/rhnException.py:66
msgid "File not found."
msgstr "Datei nicht gefunden."

#: ../common/rhnException.py:67
msgid "Architecture and OS version combination is not supported."
msgstr ""
"Diese Kombination aus Architektur und OS Version wird nicht unterstützt."

#: ../common/rhnException.py:68
msgid "Could not retrieve system data from database."
msgstr "Systemdaten konnten in der Datenbank nicht gefunden werden."

#: ../common/rhnException.py:69
msgid "Invalid arguments passed to function."
msgstr "Der Funktion wurden ungültige Werte übergeben."

#: ../common/rhnException.py:70
msgid "Unable to retrieve requested entry."
msgstr "Eintrag konnte nicht abgerufen werden."

#: ../common/rhnException.py:71
msgid "Could not update database entry."
msgstr "Datenbankeintrag konnte nicht aktualisiert werden."

#: ../common/rhnException.py:72
msgid "Unsupported server architecture."
msgstr "Serverarchitektur wird nicht unterstützt."

#: ../common/rhnException.py:73
#, python-format
msgid ""
"\n"
"     The anonymous server functionality is no longer available.\n"
"\n"
"     Please re-register this system by running rhn_register\n"
"     as root.\n"
"     Please visit https://%(hostname)s/rhn/systems/SystemEntitlements.do\n"
"     or login at https://%(hostname)s, and from the \"Overview\" tab,\n"
"     select \"Subscription Management\" to enable the service for this "
"system.\n"
"     "
msgstr ""

#: ../common/rhnException.py:82
msgid "Record not available in the database."
msgstr "Kein Eintrag in der Datenbank."

#: ../common/rhnException.py:83
msgid "Invalid value for entry."
msgstr "Ungültiger Wert."

#: ../common/rhnException.py:84
#, python-format
msgid ""
"\n"
"     This system does not have a valid entitlement for Red Hat Satellite.\n"
"     Please visit https://%(hostname)s/rhn/systems/SystemEntitlements.do\n"
"     or login at https://%(hostname)s, and from the \"Overview\" tab,\n"
"     select \"Subscription Management\" to enable the service for this "
"system.\n"
"     "
msgstr ""

#: ../common/rhnException.py:90
msgid "Channel error"
msgstr "Channel Fehler"

#: ../common/rhnException.py:91
msgid "Client session token is invalid."
msgstr "Client Session Token ist ungültig."

#: ../common/rhnException.py:92
msgid "Client session token has expired."
msgstr "Client Session ist abgelaufen."

#: ../common/rhnException.py:93
msgid "You are not authorized to retrieve the requested object."
msgstr "Sie sind nicht berechtigt dieses Objekt abzurufen."

#: ../common/rhnException.py:94
msgid "Invalid action"
msgstr "Ungültige Aktion"

#: ../common/rhnException.py:95
msgid "You are not allowed to perform administrative tasks on this system."
msgstr "Sie sind für Administative Tätigkeiten nicht freigegeben."

#: ../common/rhnException.py:97
msgid "The system is already subscribed to the specified channel."
msgstr "Dieses System ist bereits bei diesem Channel registriert."

#: ../common/rhnException.py:98
msgid "The system is not currently subscribed to the specified channel."
msgstr "Dieses System ist bei diesem Channel nicht registriert."

#: ../common/rhnException.py:99
msgid "The specified channel does not exist."
msgstr "Der angegebene Channel existiert nicht."

#: ../common/rhnException.py:100
msgid "Invalid channel version."
msgstr "Ungültige Channel-Version."

#: ../common/rhnException.py:101
msgid ""
"\n"
"     User group membership limits exceeded.\n"
"\n"
"     The current settings for your account do not allow you to add another\n"
"     user account. Please check with the organization administrator for "
"your\n"
"     account if the maximum number of users allowed to subscribe to server "
"needs\n"
"     to be changed.\n"
"     "
msgstr ""

#: ../common/rhnException.py:109
msgid ""
"\n"
"     System group membership limits exceeded.\n"
"\n"
"     The current settings for your account do not allow you to add another\n"
"     system profile. Please check with the organization administrator for "
"your\n"
"     account for modifying the maximum number of system profiles that can "
"be\n"
"     subscribed to your account.\n"
"     "
msgstr ""

#: ../common/rhnException.py:117
#, fuzzy
msgid ""
"\n"
"     Invalid architecture.\n"
"\n"
"     The architecture of the package is not supported by\n"
"     "
msgstr ""
"\n"
"     Ungültige Architektur.\n"
"\n"
"     Die Architektur dieses Paketes ist vom Red Hat Network nicht "
"unterstützt\n"
"     "

#: ../common/rhnException.py:122
msgid "Invalid RPM header"
msgstr "Ungültiger RPM Header"

#. For the uploading tools
#: ../common/rhnException.py:124
msgid "Invalid information uploaded to the server"
msgstr "Es wurden ungültige Informationen hochgeladen"

#: ../common/rhnException.py:125
msgid "Error uploading network interfaces configuration."
msgstr "Fehler beim Hochladen der Konfiguration der Netzwerk-Schnittstellen."

#: ../common/rhnException.py:126
msgid ""
"\n"
"     Package Upload Failed due to uniqueness constraint violation.\n"
"     Make sure the package does not have any duplicate dependencies or\n"
"     does not already exists on the server\n"
"     "
msgstr ""
"\n"
"     Hochladen des Paketes fehlgeschlagen. \n"
"     Bitte prüfen Sie ob das Paket keine doppelten Abhängigkeiten besitzt\n"
"      und nicht schon bereits auf dem Server vorhanden ist\n"
"     "

#: ../common/rhnException.py:131
#, fuzzy
msgid ""
"\n"
"     The --force rhnpush option is disabled on this server.\n"
"     Please contact your Satellite administrator for more help.\n"
"     "
msgstr ""
"\n"
"     Die Option --force für rhnpush wurde auf diesem Server deaktiviert. \n"
"     Bitte kontaktieren Sie den Satellite Administrator für Hilfestellung.\n"
"     "

#. 60-70: token errors
#: ../common/rhnException.py:137
msgid ""
"\n"
"     The activation token specified could not be found on the server.\n"
"     Please retry with a valid key.\n"
"     "
msgstr ""

#: ../common/rhnException.py:141
msgid "Too many systems registered using this registration token"
msgstr "Zuviele Systeme sind dieser Registration zugeordnet"

#: ../common/rhnException.py:142
msgid "Token contains invalid, obsoleted or insufficient settings"
msgstr ""
"Dieser Token enthält ungültige, obsolete oder nicht ausreichende "
"Einstellungen"

#: ../common/rhnException.py:143
msgid "Conflicting activation tokens"
msgstr "Aktivierungs-Tokens mit Konflikten"

#. 70-80: channel subscription errors
#: ../common/rhnException.py:146
msgid ""
"\n"
"     No matching base channel found for your system.\n"
"     "
msgstr ""

#: ../common/rhnException.py:149
msgid ""
"\n"
"     You do not have subscription permission to the designated channel.\n"
"     Please refer to your organization's channel or organization\n"
"     administrators for further details.\n"
"     "
msgstr ""

#: ../common/rhnException.py:154
msgid "You can not unsubscribe from base channel."
msgstr "Sie können sich von diesem Base-Channel nicht abmelden."

#: ../common/rhnException.py:155
msgid "Satellite or Proxy channel can not be subscribed."
msgstr ""

#. 80-90: server group errors
#: ../common/rhnException.py:158
msgid "There was an error while trying to join the system to its groups"
msgstr "Fehler beim Hinzufügen des Systems in die entsprechenden Gruppen"

#. 90-100: entitlement errors
#: ../common/rhnException.py:161
msgid "Unable to entitle system"
msgstr "System kann nicht berechtigt werden"

#. 100-109: e-mail and uuid related faults
#: ../common/rhnException.py:164
msgid "Maximum e-mail length violation."
msgstr "Maximale Länge der Email überschritten."

#: ../common/rhnException.py:165
msgid "This system has been previously registered."
msgstr "Dieses System wurde bereits registriert."

#: ../common/rhnException.py:166
msgid "Invalid username"
msgstr "Benutzername ungültig"

#. 140-159 applet errors
#: ../common/rhnException.py:169
msgid "Unable to look up server"
msgstr ""

#. 160-179: OSAD errors
#: ../common/rhnException.py:172
msgid "Required argument is missing"
msgstr "Benötigte Angabe fehlt"

#. 600-699: RHEL5+ EN errors
#: ../common/rhnException.py:175
msgid "No entitlement information tied to hardware"
msgstr ""

#: ../common/rhnException.py:176
msgid "Installation number is not entitling"
msgstr ""

#. 700-799: Additional user input verification errors.
#: ../common/rhnException.py:179
msgid "Maximum username length violation"
msgstr "Maximale Länge des Benutzernamen überschritten"

#: ../common/rhnException.py:180
msgid "Maximum password length violation"
msgstr "Maximale Passwortlänge überschritten"

#: ../common/rhnException.py:181
msgid "This user has read only API access. Action denied."
msgstr ""

#: ../common/rhnException.py:183
#, fuzzy
msgid "System Name cannot be less than 1 character"
msgstr "der Benutzername darf höchstens %d Zeichen lang sein"

#. 1000-1999: Proxy specific errors:
#. issued by a Proxy to the client
#: ../common/rhnException.py:187
#, fuzzy
msgid "Spacewalk Proxy error."
msgstr "RHN Proxy Fehler."

#: ../common/rhnException.py:188
#, fuzzy
msgid "Spacewalk Proxy unable to login."
msgstr "Login zum RHN Proxy nicht möglich."

#. issued by a Red Hat Server/Satellite to the proxy
#: ../common/rhnException.py:190
msgid ""
"\n"
"     Spacewalk Proxy system ID does not match a Spacewalk Proxy Server\n"
"     in the database.\n"
"     "
msgstr ""

#: ../common/rhnException.py:194
#, fuzzy
msgid "Spacewalk Proxy session token is invalid."
msgstr "RHN Proxy Session-Token ist ungültig."

#: ../common/rhnException.py:195
#, fuzzy
msgid "Spacewalk Proxy session token has expired."
msgstr "RHN Proxy Session Token abgelaufen."

#. 2000-2999: Red Hat Satellite specific errors:
#: ../common/rhnException.py:199
msgid ""
"\n"
"      user creation is not allowed via rhn_register;\n"
"     please contact your sysadmin to have your account created.\n"
"     "
msgstr ""

#: ../common/rhnException.py:203
msgid ""
"\n"
"     This satellite server is not allowed to use Inter Satellite Sync on "
"this satellite\n"
"     "
msgstr ""
"\n"
"     Diesem Satellite Server fehlt die Berechtigung für Inter Satellite Sync "
"auf diesem Satellite\n"
"     "

#: ../common/rhnException.py:206
msgid ""
"\n"
"     Inter Satellite Sync is disabled on this satellite.\n"
"     "
msgstr ""
"\n"
"     Inter Satellite Sync ist auf diesem Satellite deaktiviert.\n"
"     "

#. 3000-3999: XML dumper errors:
#: ../common/rhnException.py:211
msgid "Invalid datatype passed"
msgstr "Es wurde ein ungültiger Datentyp übergeben"

#: ../common/rhnException.py:212
msgid "Unable to retrieve channel"
msgstr "Channels konnten nicht abgerufen werden"

#: ../common/rhnException.py:213
msgid "Unable to retrieve package"
msgstr "Pakete konnten nicht abgerufen werden"

#: ../common/rhnException.py:214
msgid "Unable to retrieve erratum"
msgstr "Erratum konnte nicht abgerufen werden"

#: ../common/rhnException.py:215
msgid "File is missing"
msgstr "Datei nicht vorhanden"

#: ../common/rhnException.py:216
msgid "Function retrieval error"
msgstr ""

#: ../common/rhnException.py:217
msgid "Function execution error"
msgstr ""

#: ../common/rhnException.py:218
msgid "Missing version string"
msgstr "Es wurde keine Version angegeben"

#: ../common/rhnException.py:219
msgid "Invalid version string"
msgstr "Ungültige Version"

#: ../common/rhnException.py:220
msgid "Mismatching versions"
msgstr "Versionen stimmen nicht überein"

#: ../common/rhnException.py:221
msgid "Invalid channel version"
msgstr "Ungültige Channel-Version"

#: ../common/rhnException.py:222
msgid "No comps file for channel"
msgstr "Keine Chomps-Datei für dem Channel"

#: ../common/rhnException.py:223
msgid "Unable to retrieve comps file"
msgstr "Comps-Datei kann nicht abgerufen werden."

#. 4000 - 4999: config management errors
#: ../common/rhnException.py:226
msgid "Configuration action missing"
msgstr ""

#: ../common/rhnException.py:227
msgid "File too large"
msgstr "Datei zu gross"

#: ../common/rhnException.py:228
msgid "File contains binary data"
msgstr "Datei enthält binäre Daten"

#: ../common/rhnException.py:229
msgid "Configuration channel is not empty"
msgstr "Konfigurations-Channel enthält Daten"

#: ../common/rhnException.py:230
msgid "Permission error"
msgstr "Zugriff nicht erlaubt"

#: ../common/rhnException.py:231
msgid "Content missing for configuration file"
msgstr "Kein Inhalt für Konfigurationsdatei"

#: ../common/rhnException.py:232
msgid "Template delimiters not specified"
msgstr "Die Template Trennzeichen sind nicht spezifiziert"

#: ../common/rhnException.py:233
msgid "Configuration channel does not exist"
msgstr "Konfigurations-Channel existiert nicht"

#: ../common/rhnException.py:234
msgid "Configuration channel already exists"
msgstr "Konfigrations-Channel bereits vorhanden"

#: ../common/rhnException.py:235
msgid "File missing from configuration channel"
msgstr "Die Datei aus dem Konfigurationskanal fehlt"

#: ../common/rhnException.py:236
msgid "Different revision of this file is uploaded"
msgstr "Eine andere Version dieser Datei wurde breits hochgeladen"

#: ../common/rhnException.py:237
msgid "File already uploaded to configuration channel"
msgstr "Datei wurde breits in den Konfigations-Channel hochgeladen"

#: ../common/rhnException.py:238
msgid "File size exceeds remaining quota space"
msgstr "Die Dateigröße überschreitet die verbleibende Quota (Speicherplatz)"

#: ../common/rhnException.py:239
msgid "Full path of file must be specified"
msgstr "Der vollständige Datei-Pfad muss angegeben werden"

#: ../common/rhnException.py:240
msgid "Invalid revision number"
msgstr "Ungültige Revisionsnummer"

#: ../common/rhnException.py:241
msgid "Cannot compare files of different file type"
msgstr ""
"Ein Vergeich zwischen verschiedenen Datei-Typen kann nicht erstellt werden"

#. 5000 - 5999: client content uploading errors
#. 5000 - 5099: crash reporting errors
#: ../common/rhnException.py:245
msgid "Crash information is invalid or incomplete"
msgstr ""

#: ../common/rhnException.py:246
msgid "Crash file information is invalid or incomplete"
msgstr ""

#: ../common/rhnException.py:247
msgid "Error composing crash directory path"
msgstr ""

#: ../common/rhnException.py:248
msgid "Error composing crash file path"
msgstr ""

#: ../common/rhnException.py:249 ../common/rhnException.py:256
#, fuzzy
msgid "Invalid content encoding"
msgstr "Ungültiger Feldcode"

#: ../common/rhnException.py:250
#, fuzzy
msgid "Invalid crash name"
msgstr "Ungültiger Paketname"

#: ../common/rhnException.py:251
msgid "Crash reporting is disabled for this organization"
msgstr ""

#. 5100 - 5199: scap results reporting error
#: ../common/rhnException.py:253
msgid "SCAP results file transfer is invalid or incomplete"
msgstr ""

#: ../common/rhnException.py:254
msgid "Error composing directory path for detailed SCAP results"
msgstr ""

#: ../common/rhnException.py:255
msgid "Error composing file path for detailed SCAP results"
msgstr ""

#: ../common/rhnException.py:303
msgid ""
"\n"
"     An error has occurred while processing your request. If this problem\n"
"     persists please enter a bug report at bugzilla.redhat.com.\n"
"     If you choose to submit the bug report, please be sure to include\n"
"     details of what you were trying to do when this error occurred and\n"
"     details on how to reproduce this problem.\n"
msgstr ""
"\n"
"     Bei der Bearbeitung Ihrer Anfrage trat ein Fehler auf. Falls dieses "
"Problem\n"
"     weiterhin auftritt, reichen Sie bitte einen Fehlerbericht unter "
"bugzilla.redhat.com ein.\n"
"     Falls Sie sich dazu entschließen, einen Fehlerbericht einzureichen, "
"stellen Sie bitte sicher,\n"
"     dass Sie Details zu den von Ihnen durchgeführten Schritten liefern, als "
"dieser Fehler auftrat,\n"
"     sowie Informationen, wie dieses Problem reproduziert werden kann.\n"

#: ../common/rhnException.py:355
#, python-format
msgid ""
"Error Message:\n"
"    %s\n"
msgstr ""
"Fehlermeldung:\n"
"    %s\n"

#: ../common/rhnException.py:357
#, python-format
msgid "Error Class Code: %s\n"
msgstr "Fehlerklasse-Code: %s\n"

#: ../common/rhnException.py:360
#, python-format
msgid "Error Class Info: %s\n"
msgstr "Fehlerklasse-Information: %s\n"

#: ../common/rhnException.py:362
#, python-format
msgid "Explanation: %s"
msgstr "Erklärung: %s"

#~ msgid "Invalid Organization Credentials"
#~ msgstr "Ungültige Organisations-Zugangsdaten"

#~ msgid "User `%s' not a member of organization %s"
#~ msgstr "der Benutzer '%s' ist nicht Mitglied der Organisation %s"

#~ msgid "Not a valid Country: %s"
#~ msgstr "Kein gültiges Land: %s"

#~ msgid "Insufficient subscription permissions for release, arch (%s, %s)"
#~ msgstr "Ungenügende Berechtigung für Release, Arch (%s, %s)"

#~ msgid "Invalid value %s (type %s)"
#~ msgstr "Ungültiger Wert %s (Typ %s)"

#~ msgid "Unable to retrieve package header %s"
#~ msgstr "Konnte Paket-Header %s nicht abrufen"

#~ msgid "Invalid value for %s in package tuple: %s (%s)"
#~ msgstr "Ungültiger Wert für %s in Pakettupel: %s (%s)"

#~ msgid "Invalid package parameter %s (%s)"
#~ msgstr "ungültiger Paketparameter (%s) %s"

#~ msgid "Outage mode"
#~ msgstr "Nichtverfügbarkeits-Modus"

#~ msgid "Can not create new entry."
#~ msgstr "Neuer Eintrag kann nicht erstellt werden."

#~ msgid "Account limits exceeded."
#~ msgstr "Benutzerkonto-Limits überschritten."

#~ msgid "Invalid product registration code."
#~ msgstr "Ungültiger Produktregistrierungs-Code."

#~ msgid "Invalid Architecture and OS release combination."
#~ msgstr "Ungültige Kombination aus Architektur und OS Version. "

#~ msgid "LDAP operation failed."
#~ msgstr "LDAP-Vorgang fehlgeschlagen."

#~ msgid ""
#~ "Backend RPM database failure: can not retrieve requested information."
#~ msgstr "Abfrage der RPM Datenbank fehlgeschlagen."

#~ msgid "Invalid ORG_ID requested"
#~ msgstr "Ungültige ORG_ID"

#~ msgid ""
#~ "\n"
#~ "     Incompatible architectures.\n"
#~ "\n"
#~ "     The architecture of the package you are trying to upload is not\n"
#~ "     compatible with the channel architecture.\n"
#~ "     "
#~ msgstr ""
#~ "\n"
#~ "     Inkompatible Architekturen.\n"
#~ "\n"
#~ "     Die Architektur des Paketes welches Sie hochladen wollten ist nicht\n"
#~ "     kompatibel mit der Architektur des Channels.\n"
#~ "     "

#~ msgid ""
#~ "\n"
#~ "     Invalid channel.\n"
#~ "\n"
#~ "     The channel you have specified does not exist.\n"
#~ "     "
#~ msgstr ""
#~ "\n"
#~ "     Ungültiger Channel.\n"
#~ "\n"
#~ "     Der angegebene Channel existiert nicht.\n"
#~ "     "

#~ msgid "Changing e-mail address is not supported."
#~ msgstr "Ändern der Emailadresse ist nicht unterstützt."

#~ msgid "Service for your account has been disabled."
#~ msgstr "Der Dienst unter ihrem Zugang wurde eingestellt."

#~ msgid "Email address not validated; service disabled"
#~ msgstr "Emailadresse wurde nicht überprüft, Service nicht verfügbar"

#~ msgid "Survey not filled out; service disabled"
#~ msgstr "Umfrage nicht ausgefüllt, Service nicht verfügbar"

#~ msgid "Bugzilla erratum import error"
#~ msgstr "Fehler beim Import eines Bugzilla Erratum"

#~ msgid "Missing HTTP header information"
#~ msgstr "Benötigte HTTP Header Informationen konnten nicht gefunden werden"

#~ msgid "The package's checksum signature does not match the header one"
#~ msgstr ""
#~ "Die Prüfsumme der Signatur des Paketes stimmt nicht mir derjenigen aus "
#~ "dem Header überein"

#~ msgid "Header information does not match package metainformation"
#~ msgstr "Header-Information stimmen nicht mit den Metadaten überein"

#~ msgid "Package with a different signature already uploaded"
#~ msgstr "Paket mit unterschiedlicher Signatur bereits hochgeladen"

#~ msgid "Not an RPM package"
#~ msgstr "Kein RPM Paket"

#~ msgid "Unsigned RPM package"
#~ msgstr "Unsigniertes RPM Paket"

#~ msgid "Incompatible package and channel architectures"
#~ msgstr "Paket und Channel Architekturen sind nicht kompatibel"

#~ msgid "Incompatible checksum type"
#~ msgstr "Typ der Prüfsumme nicht kompatibel"

#~ msgid "Invalid Entitlement Number"
#~ msgstr "Falsche Berechtigungsnummer"

#~ msgid "Access denied to kickstart tree"
#~ msgstr "Zugriff zum Kickstart-Tree verweigert"

#~ msgid "Could not find kickstart file"
#~ msgstr "Kickstart-Datei nicht gefunden"

#~ msgid "Invalid erratum name"
#~ msgstr "Ungültiger Name des Erratum"

#~ msgid "Invalid satellite certificate"
#~ msgstr "Satellite-Zertifikat ungültig"

#~ msgid "The speicified item is not present in the input"
#~ msgstr "Das angegebene Feld existiert nicht in der Eingabe"

#~ msgid "Invalid user role"
#~ msgstr "Ungültige Benutzerrolle"

#~ msgid "Invalid server group"
#~ msgstr "Ungültige Servergruppe"

#~ msgid "Invalid channel family"
#~ msgstr "Ungültige Channel-Familie"
